### PR TITLE
Ch update to php 8

### PR DESCRIPTION
**Pull request by chartjes**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

These changes update this repo to work with PHP 8.0.0 and PHP 9.4.3. It adds new dependencies and contains updated tests.

### CODE REVIEW

**Comment by weierophinney** [comment]
Hey, Chris! Thanks a ton for this!

Before I review, can you add a sign-off message to your commits? Instructions for doing so after-the-fact are here: https://github.com/laminas/.github/blob/master/CONTRIBUTING.md#adding-signoffs-after-the-fact

(This is the way you tell us that you're giving us rights to the code you contribute.)

Thanks in advance!

**Comment by chartjes** [comment]
I *think* I did it right, please let me know.

**Comment by weierophinney** [comment]
> I *think* I did it right, please let me know.

Not quite there - basically, you need the following line at the end of your commit message:

```text
Signed-Off-By: Chris Hartjes <whateveryouremailaddressis>
```

(You can use the generated email address from github if you want added privacy.)

These are generally auto-generated for you when you use the `-s` switch with `git commit` or the `--signoff` switch with `git rebase`; alternately, you can do it via a message template (that's the route I go personally, but mainly because the bulk of the repos I provide patches for use it).

**Comment by chartjes** [comment]
Okay, let me see about forcing a commit with that in it (I have tried several times but it hasn't worked).

On Mon, Nov 30, 2020, at 4:21 PM, weierophinney wrote:
> 

>> I *think* I did it right, please let me know.

> Not quite there - basically, you need the following line at the end of your commit message:

> `Signed-Off-By: Chris Hartjes <whateveryouremailaddressis>
`

**Comment by weierophinney** [comment]
There's something off about it, but I'm not sure what - however, I also discovered I can manually approve it, and since you've tried... focus the efforts on updating the Travis-CI config so that tests only run against PHP 7.3 and up, so we can see if the patch works correctly. :smile:

**Comment by weierophinney** [comment]
@chartjes I pushed some updates for you; the main issue was with usage of `$someInstance::class`, as dynamic instance usage of the `::class` pseudo-constant is only available in PHP 8. I also updated the test matrix to reflect the versions now listed in `composer.json`.

Thanks a ton for this!

**Pull request merged**
